### ISSUE TITLE
Surtr's Menace gives multiple boosts

### ISSUE THREAD

**Issue by Flametix** [laqieer/fe7-jp-stunning-tribble#34]
**Describe the bug**
Surtr is getting too many stat boosts from Surtr's Menace.

**To Reproduce**
1. Start Chapter 104
2. See scary Surtr

**Expected behavior**
Surtr's Menace should only buff Surtr once.

**Screenshots**
![image](https://user-images.githubusercontent.com/44883711/91898735-2f271380-ec6a-11ea-9047-012c9809035b.png)
![image](https://user-images.githubusercontent.com/44883711/91901106-baee6f00-ec6d-11ea-9d74-f3e9b28d61e5.png)

**Environment (please complete the following information):**
 - Emulator: VisualBoyAdvance-M
 - Flashcart: n/a
 - Version: 5.9

**Save (please attach them here directly):**
 - Game Save: https://gofile.io/d/E7UJOG (can't upload to github)
 - Emulator Save: same link [e.g. *.sgm]

**Additional context**
It's still possible to win if you run away.

**Comment by laqieer** [comment]
Buff and debuff are **repeatable** in this hack. This game design is different from original smart phone game. You cannot defeat Surtr in this chapter, so you need to run and run now. Surtr can be killed in later chapter (Laegjarn has a custom skill to restrain his Menace).
Watch these [videos](https://space.bilibili.com/343025) if you have difficulty with some chapters.

**Comment by Flametix** [comment]
Oh ok I didn't know. Thanks for the tips.
